#pragma execution_character_set("utf-8")

#include "projectwriter.h"

#include "designitem.h"
#include "uiwriter.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>

namespace {

bool writeTextFile(const QString &path, const QString &content)
{
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text))
        return false;
    f.write(content.toUtf8());
    f.close();
    return true;
}

QString fixExportUrls(const QString &qss)
{
    QString result = qss;
    static const QRegularExpression re("url\\([\\s]*([^)]*?)[\\s]*\\)");
    QRegularExpressionMatchIterator it = re.globalMatch(qss);
    QStringList replacements;
    while (it.hasNext())
    {
        const QRegularExpressionMatch m = it.next();
        QString path = m.captured(1).trimmed();
        if (path.startsWith(QLatin1Char('"')))
            path = path.mid(1);
        if (path.endsWith(QLatin1Char('"')))
            path.chop(1);
        if (path.startsWith(QLatin1String("/usr/")))
            replacements << QStringLiteral("url(QSS_IMG/") + QFileInfo(path).fileName() + QLatin1Char(')');
        else
            replacements << m.captured(0);
    }
    int offset = 0;
    QRegularExpressionMatchIterator it2 = re.globalMatch(result);
    int i = 0;
    while (it2.hasNext())
    {
        const QRegularExpressionMatch m = it2.next();
        if (i >= replacements.size())
            break;
        result.replace(m.capturedStart() + offset, m.capturedLength(), replacements.at(i));
        offset += replacements.at(i).length() - m.capturedLength();
        ++i;
    }
    return result;
}

} // namespace

bool ProjectWriter::writeProject(const QString &dir,
                                 const QList<DesignItem *> &items,
                                 const QString &styleText,
                                 const QString &windowTitle,
                                 const QString &stylesDir,
                                 QString *error)
{
    QDir d(dir);
    if (!d.exists())
    {
        if (!d.mkpath(QStringLiteral(".")))
        {
            if (error)
                *error = QStringLiteral("无法创建工程目录。");
            return false;
        }
    }

    const QString uiFile = dir + QStringLiteral("/MyProject.ui");
    if (!UiWriter::writeUi(uiFile, items, windowTitle, error))
        return false;

    const QString qss = fixExportUrls(styleText);
    if (!writeTextFile(dir + QStringLiteral("/MyProject.qss"), qss))
    {
        if (error)
            *error = QStringLiteral("无法写入 MyProject.qss。");
        return false;
    }

    // copy icon folder used by some styles (e.g. MacOS.qss)
    const QString imgSrc = stylesDir + QStringLiteral("/QSS_IMG");
    if (QDir(imgSrc).exists())
    {
        QDir().mkpath(dir + QStringLiteral("/QSS_IMG"));
        Q_FOREACH (const QString &img,
                   QDir(imgSrc).entryList(QDir::Files | QDir::NoDotAndDotDot))
        {
            QFile::copy(imgSrc + QLatin1Char('/') + img,
                        dir + QStringLiteral("/QSS_IMG/") + img);
        }
    }

    const QString pro =
        QStringLiteral("# Generated by QssDesigner\n"
                       "QT += core gui widgets uitools\n"
                       "greaterThan(QT_MAJOR_VERSION, 4): QT += widgets\n"
                       "\n"
                       "CONFIG += c++11\n"
                       "TARGET = MyProject\n"
                       "TEMPLATE = app\n"
                       "\n"
                       "SOURCES += main.cpp mainwindow.cpp\n"
                       "HEADERS += mainwindow.h\n");
    if (!writeTextFile(dir + QStringLiteral("/MyProject.pro"), pro)) {
        if (error)
            *error = QStringLiteral("无法写入 MyProject.pro。");
        return false;
    }

    const QString mainh =
        QStringLiteral("#ifndef MAINWINDOW_H\n"
                       "#define MAINWINDOW_H\n"
                       "\n"
                       "#include <QMainWindow>\n"
                       "\n"
                       "class MainWindow : public QMainWindow\n"
                       "{\n"
                       "    Q_OBJECT\n"
                       "\n"
                       "public:\n"
                       "    explicit MainWindow(QWidget *parent = 0);\n"
                       "    bool loadFromUi(const QString &uiPath, const QString &qssPath);\n"
                       "};\n"
                       "\n"
                       "#endif // MAINWINDOW_H\n");
    if (!writeTextFile(dir + QStringLiteral("/mainwindow.h"), mainh)) {
        if (error)
            *error = QStringLiteral("无法写入 mainwindow.h。");
        return false;
    }

    const QString maincpp =
        QStringLiteral("#include \"mainwindow.h\"\n"
                       "\n"
                       "#include <QFile>\n"
                       "#include <QDockWidget>\n"
                       "#include <QMenuBar>\n"
                       "#include <QStatusBar>\n"
                       "#include <QToolBar>\n"
                       "#include <QUiLoader>\n"
                       "\n"
                       "MainWindow::MainWindow(QWidget *parent)\n"
                       "    : QMainWindow(parent)\n"
                       "{\n"
                       "}\n"
                       "\n"
                       "bool MainWindow::loadFromUi(const QString &uiPath, const QString &qssPath)\n"
                       "{\n"
                       "    QFile uiFile(uiPath);\n"
                       "    if (!uiFile.open(QIODevice::ReadOnly))\n"
                       "        return false;\n"
                       "\n"
                       "    QUiLoader loader;\n"
                       "    QWidget *ui = loader.load(&uiFile, this);\n"
                       "    uiFile.close();\n"
                       "    if (!ui)\n"
                       "        return false;\n"
                       "\n"
                       "    if (QMainWindow *mw = qobject_cast<QMainWindow *>(ui)) {\n"
                       "        setCentralWidget(mw->centralWidget());\n"
                       "        setWindowTitle(mw->windowTitle());\n"
                       "        setWindowIcon(mw->windowIcon());\n"
                       "        if (mw->menuBar())\n"
                       "            setMenuBar(mw->menuBar());\n"
                       "        if (mw->statusBar())\n"
                       "            setStatusBar(mw->statusBar());\n"
                       "        Q_FOREACH (QToolBar *tb, mw->findChildren<QToolBar *>())\n"
                       "            addToolBar(tb);\n"
                       "        Q_FOREACH (QDockWidget *dw, mw->findChildren<QDockWidget *>())\n"
                       "            addDockWidget(Qt::LeftDockWidgetArea, dw);\n"
                       "        mw->deleteLater();\n"
                       "    } else {\n"
                       "        setCentralWidget(ui);\n"
                       "    }\n"
                       "\n"
                       "    QFile qss(qssPath);\n"
                       "    if (qss.open(QIODevice::ReadOnly)) {\n"
                       "        setStyleSheet(QString::fromUtf8(qss.readAll()));\n"
                       "        qss.close();\n"
                       "    }\n"
                       "    resize(960, 640);\n"
                       "    return true;\n"
                       "}\n");
    if (!writeTextFile(dir + QStringLiteral("/mainwindow.cpp"), maincpp)) {
        if (error)
            *error = QStringLiteral("无法写入 mainwindow.cpp。");
        return false;
    }

    const QString mainCpp =
        QStringLiteral("#include <QApplication>\n"
                       "#include <QDir>\n"
                       "#include <QFileInfo>\n"
                       "\n"
                       "#include \"mainwindow.h\"\n"
                       "\n"
                       "int main(int argc, char *argv[])\n"
                       "{\n"
                       "    QApplication app(argc, argv);\n"
                       "\n"
                       "    MainWindow w;\n"
                       "    QString dir = QCoreApplication::applicationDirPath();\n"
                       "    if (!QFileInfo(dir + QStringLiteral(\"/MyProject.ui\")).exists())\n"
                       "        dir = QDir::currentPath();\n"
                       "\n"
                       "    if (!w.loadFromUi(dir + QStringLiteral(\"/MyProject.ui\"),\n"
                       "                       dir + QStringLiteral(\"/MyProject.qss\"))) {\n"
                       "        w.setWindowTitle(QStringLiteral(\"MyProject\"));\n"
                       "        w.resize(960, 640);\n"
                       "    }\n"
                       "    w.show();\n"
                       "    return app.exec();\n"
                       "}\n");
    if (!writeTextFile(dir + QStringLiteral("/main.cpp"), mainCpp)) {
        if (error)
            *error = QStringLiteral("无法写入 main.cpp。");
        return false;
    }

    return true;
}
